=== andrewmccaffreynist/CDASources/hitspValidation2/build/web/WEB-INF/docTypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="urn:gov:nist:cdaGuidelineValidator" xmlns="urn:gov:nist:cdaGuidelineValidator"
    elementFormDefault="qualified">

    <xs:element name="documentTypes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="documentType" type="DocumentType" minOccurs="1"
                    maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="DocumentType">
        <xs:sequence>
            <xs:element name="displayName" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="validation" type="Validation" minOccurs="1" maxOccurs="1" />
            <xs:element name="dependencies" type="Dependencies" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="backendOnly" type="xs:boolean" use="optional" default="false" />
    </xs:complexType>

    <xs:complexType name="Validation">        
        <xs:simpleContent>
            <xs:extension base="xs:string">                
                <xs:attribute name="type" type="ValidValidations" use="required"/>                
            </xs:extension>
        </xs:simpleContent>        
    </xs:complexType>

    <xs:simpleType name="ValidValidations">
        <xs:restriction base="xs:string">
            <xs:enumeration value="schema"/>
            <xs:enumeration value="schematron"/>
        </xs:restriction>
    </xs:simpleType>       
    
    <xs:complexType name="Dependencies">
        <xs:sequence>
            <xs:element name="dependency" type="Dependency" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Dependency">
        <xs:simpleContent>
            <xs:extension base="xs:IDREF">                
                <xs:attribute name="sequenceNumber" type="xs:int" use="required"/>                
            </xs:extension>
        </xs:simpleContent>           
    </xs:complexType>

</xs:schema>

=== andrewmccaffreynist/CDASources/muValidationCR/build/web/WEB-INF/docTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<documentTypes xmlns="urn:gov:nist:cdaGuidelineValidator"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:hl7-org:v3 docTypes.xsd">

    <documentType id="ccdMu">
        <displayName>CCD (Meaningful Use)</displayName>
        <description>HL7 Continuity of Care Document (for Meaningful Use)</description>
        <validation type="schematron">http://localhost:8084/muValidation/schematron/ccd-mu/ccd.sch</validation>
        <dependencies>
            <dependency sequenceNumber="1">cdar2</dependency>
        </dependencies>
    </documentType>

    <documentType id="cdar2">
        <displayName>CDA R2</displayName>
        <description>HL7 CDA R2 (with no extensions)</description>
        <validation type="schema"
            >http://localhost:8084/muValidation/schema/cdar2/infrastructure/cda/CDA.xsd</validation>
        <dependencies/>
    </documentType>

</documentTypes>

=== andrewmccaffreynist/CDASources/hitspValidation2/build/web/WEB-INF/docTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<documentTypes xmlns="urn:gov:nist:cdaGuidelineValidator"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:hl7-org:v3 docTypes.xsd">

   <documentType id="cdar2">
        <displayName>CDA R2</displayName>
        <description>HL7 CDA R2 (with no extensions)</description>
        <validation type="schema"
            >http://localhost:8084/hitspValidation2/schema/cdar2/infrastructure/cda/CDA.xsd</validation>
        <dependencies/>
    </documentType>
    
    <documentType id="cdar2c32" backendOnly="true">
        <displayName>CDA R2 (With HITSP Extensions)</displayName>
        <description>HL7 CDA R2 (With HITSP Extensions)</description>
        <validation type="schema"
            >http://localhost:8084/hitspValidation2/schema/cdar2c32/infrastructure/cda/C32_CDA.xsd</validation>
    </documentType>
    
    
    <documentType id="ccd">
        <displayName>CCD (Meaningful Use)</displayName>
        <description>HL7 Continuity of Care Documen)</description>
        <validation type="schematron">http://localhost:8084/hitspValidation2/schematron/ccd/ccd.sch</validation>
        <dependencies>
            <dependency sequenceNumber="1">cdar2</dependency>
        </dependencies>
    </documentType>

    <documentType id="cda4CdtIhe" backendOnly="true">
        <displayName>CDA4CDT (header only and with IHE modifications)</displayName>
        <description>HL7 CDA For Common Document Types (CDA4CDT) -- header only and with IHE modifications</description>
        <validation type="schematron">http://localhost:8084/hitspValidation2/schematron/cda4cdt/HandP.IHE.PCC.sch</validation>
        <dependencies>
            <dependency sequenceNumber="1">cdar2</dependency>
        </dependencies>
    </documentType>
    
    <documentType id="c32_v_2_5_c83_2_0">
        <displayName>HITSP/C32 v2.5 -- HITSP/C83 v2.0</displayName>
        <description>HITSP/C32 v2.5 Summary Documents Using HL7 CCD</description>
        <validation type="schematron">http://localhost:8084/hitspValidation2/schematron/c32_v_2_5_c83_2_0/HITSP_C32.sch</validation>
        <dependencies>
            <dependency sequenceNumber="1">cdar2c32</dependency>
            <!--
            <dependency sequenceNumber="2">cda4CdtIhe</dependency>
            -->
            <dependency sequenceNumber="3">ccd</dependency>
        </dependencies>
    </documentType>


</documentTypes>
